config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  # validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # hello
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(book_mark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def book_mark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render new_list_path, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f|%>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <nav class="navbar navbar-background mb-3">
      <div class="container">
        <div class="container-fluid d-flex justify-content-between align-items-center">
          <%= link_to lists_path, class: 'navbar-btn-no-border' do %>
            WatchList
          <% end %>
          <%= link_to 'Add list', new_list_path, class: 'navbar-btn' %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="lists-main-heading">Movie lists</h1>
  <div class="d-flex gap-3 flex-wrap justify-content-start">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class: 'text-decoration-none text-dark' do %>
        <div class="card" style="width: 18rem">
          <%= cl_image_tag list.photo.key, alt: "text", class: 'card-img-top card-image-size'%>
          <div class="card-body">
            <h5 class="card-title "><%= list.name %></h5>
            <%# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%# <%= f.input :image_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <p>
    <%= link_to 'Add bookmark', new_list_bookmark_path(@list), class: 'btn btn-secondary'%>
  </p>
  <div class="d-flex gap-3 justify-content-start flex-wrap">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card" style="width: 18rem;">
      <%= image_tag bookmark.movie.poster_url, alt: "text", class: "card-image-size" %>
        <div class="card-body d-flex flex-column justify-content-between">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.comment %></p>
          <%= link_to 'Delete bookmark',
            bookmark_path(bookmark),
            data: {turbo_method: 'delete', turbo_confirm: 'Delete bookmark?'},
            class: 'btn btn-primary'
          %>
        </div>
      </div>
    <% end %>
  </div>

</div>